import { Product, Store, UserRole } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Платье женское вечернее',
    price: 4500,
    priceRange: 'от 4500 сом',
    category: 'Женская одежда',
    color: 'Черный',
    sizes: [
      { system: 'RU', value: '42' },
      { system: 'RU', value: '44' },
      { system: 'RU', value: '46' },
      { system: 'EU', value: 'S' },
      { system: 'EU', value: 'M' },
      { system: 'Letter', value: 'S' },
      { system: 'Letter', value: 'M' },
    ],
    images: ['/placeholder1.jpg'],
    description: 'Элегантное вечернее платье из атласа. Идеально подходит для особых случаев.',
    seller: {
      id: 's1',
      name: 'Elegance Fashion',
      contact: '+996 555 123 456',
      whatsapp: '+996555123456',
      instagram: 'elegance_fashion_kg',
    },
    bodyMeasurements: {
      chest: 88,
      waist: 68,
      hips: 94,
      shoulders: 38,
      sleeve: 58,
    },
    garmentMeasurements: {
      length: 90,
      chest: 96,
      waist: 74,
      hips: 102,
      sleeve: 60,
    },
  },
  {
    id: '2',
    name: 'Куртка зимняя мужская',
    price: 8500,
    priceRange: 'от 8500 сом',
    category: 'Мужская одежда',
    color: 'Темно-синий',
    sizes: [
      { system: 'RU', value: '48' },
      { system: 'RU', value: '50' },
      { system: 'RU', value: '52' },
      { system: 'EU', value: 'L' },
      { system: 'EU', value: 'XL' },
      { system: 'Letter', value: 'L' },
      { system: 'Letter', value: 'XL' },
    ],
    images: ['/placeholder2.jpg'],
    description: 'Теплая зимняя куртка с утеплителем. Водоотталкивающая ткань.',
    seller: {
      id: 's2',
      name: 'SportWear KG',
      contact: '+996 555 234 567',
      whatsapp: '+996555234567',
      instagram: 'sportwear_kg',
    },
    bodyMeasurements: {
      chest: 104,
      waist: 92,
      shoulders: 46,
      sleeve: 65,
    },
    garmentMeasurements: {
      length: 75,
      chest: 112,
      waist: 100,
      sleeve: 68,
    },
  },
  {
    id: '3',
    name: 'Футболка базовая хлопковая',
    price: 1200,
    priceRange: 'от 1200 сом',
    category: 'Женская одежда',
    color: 'Белый',
    sizes: [
      { system: 'RU', value: '40' },
      { system: 'RU', value: '42' },
      { system: 'RU', value: '44' },
      { system: 'EU', value: 'XS' },
      { system: 'EU', value: 'S' },
      { system: 'Letter', value: 'XS' },
      { system: 'Letter', value: 'S' },
    ],
    images: ['/placeholder3.jpg'],
    description: 'Базовая хлопковая футболка для повседневной носки.',
    seller: {
      id: 's3',
      name: 'Basic Store',
      contact: '+996 555 345 678',
      whatsapp: '+996555345678',
      instagram: 'basic_store_kg',
    },
    bodyMeasurements: {
      chest: 84,
      waist: 66,
      hips: 90,
    },
    garmentMeasurements: {
      length: 65,
      chest: 92,
      waist: 82,
      hips: 98,
    },
  },
  {
    id: '4',
    name: 'Джинсы мужские slim fit',
    price: 3200,
    priceRange: 'от 3200 сом',
    category: 'Мужская одежда',
    color: 'Синий',
    sizes: [
      { system: 'RU', value: '46' },
      { system: 'RU', value: '48' },
      { system: 'RU', value: '50' },
      { system: 'EU', value: 'M' },
      { system: 'EU', value: 'L' },
      { system: 'Letter', value: '30' },
      { system: 'Letter', value: '32' },
    ],
    images: ['/placeholder4.jpg'],
    description: 'Классические джинсы slim fit из плотного денима.',
    seller: {
      id: 's4',
      name: 'Denim World',
      contact: '+996 555 456 789',
      whatsapp: '+996555456789',
      instagram: 'denim_world_kg',
    },
    bodyMeasurements: {
      waist: 84,
      hips: 98,
    },
    garmentMeasurements: {
      length: 104,
      chest: 96,
      waist: 88,
      hips: 102,
    },
  },
  {
    id: '5',
    name: 'Блузка офисная',
    price: 2800,
    priceRange: 'от 2800 сом',
    category: 'Женская одежда',
    color: 'Светло-голубой',
    sizes: [
      { system: 'RU', value: '42' },
      { system: 'RU', value: '44' },
      { system: 'RU', value: '46' },
      { system: 'EU', value: 'S' },
      { system: 'EU', value: 'M' },
      { system: 'Letter', value: 'S' },
      { system: 'Letter', value: 'M' },
    ],
    images: ['/placeholder5.jpg'],
    description: 'Элегантная офисная блузка из хлопка с добавлением эластана.',
    seller: {
      id: 's5',
      name: 'Office Style',
      contact: '+996 555 567 890',
      whatsapp: '+996555567890',
      instagram: 'office_style_kg',
    },
    bodyMeasurements: {
      chest: 86,
      waist: 64,
      shoulders: 36,
      sleeve: 56,
    },
    garmentMeasurements: {
      length: 62,
      chest: 94,
      waist: 70,
      sleeve: 58,
    },
  },
  {
    id: '6',
    name: 'Пуховик детский',
    price: 5500,
    priceRange: 'от 5500 сом',
    category: 'Детская одежда',
    color: 'Розовый',
    sizes: [
      { system: 'RU', value: '122' },
      { system: 'RU', value: '128' },
      { system: 'RU', value: '134' },
      { system: 'EU', value: '7Y' },
      { system: 'EU', value: '8Y' },
      { system: 'Letter', value: '7Y' },
      { system: 'Letter', value: '8Y' },
    ],
    images: ['/placeholder6.jpg'],
    description: 'Теплый пуховик для детей с утеплителем.',
    seller: {
      id: 's6',
      name: 'Kids Fashion',
      contact: '+996 555 678 901',
      whatsapp: '+996555678901',
      instagram: 'kids_fashion_kg',
    },
    bodyMeasurements: {
      chest: 68,
      waist: 60,
      shoulders: 32,
      sleeve: 42,
    },
    garmentMeasurements: {
      length: 52,
      chest: 76,
      waist: 68,
      sleeve: 44,
    },
  },
  {
    id: '7',
    name: 'Костюм тройка мужской',
    price: 15000,
    priceRange: 'от 15000 сом',
    category: 'Мужская одежда',
    color: 'Серый',
    sizes: [
      { system: 'RU', value: '48' },
      { system: 'RU', value: '50' },
      { system: 'RU', value: '52' },
      { system: 'EU', value: 'L' },
      { system: 'EU', value: 'XL' },
      { system: 'Letter', value: 'L' },
      { system: 'Letter', value: 'XL' },
    ],
    images: ['/placeholder7.jpg'],
    description: 'Классический костюм тройка из шерстяной ткани.',
    seller: {
      id: 's7',
      name: 'Formal Wear',
      contact: '+996 555 789 012',
      whatsapp: '+996555789012',
      instagram: 'formal_wear_kg',
    },
    bodyMeasurements: {
      chest: 102,
      waist: 90,
      shoulders: 45,
      sleeve: 64,
    },
    garmentMeasurements: {
      length: 72,
      chest: 110,
      waist: 98,
      sleeve: 66,
    },
  },
  {
    id: '8',
    name: 'Юбка карандаш',
    price: 2200,
    priceRange: 'от 2200 сом',
    category: 'Женская одежда',
    color: 'Красный',
    sizes: [
      { system: 'RU', value: '42' },
      { system: 'RU', value: '44' },
      { system: 'RU', value: '46' },
      { system: 'EU', value: 'S' },
      { system: 'EU', value: 'M' },
      { system: 'Letter', value: 'S' },
      { system: 'Letter', value: 'M' },
    ],
    images: ['/placeholder8.jpg'],
    description: 'Стильная юбка карандаш из эластичной ткани.',
    seller: {
      id: 's8',
      name: 'Trendy Clothes',
      contact: '+996 555 890 123',
      whatsapp: '+996555890123',
      instagram: 'trendy_clothes_kg',
    },
    bodyMeasurements: {
      waist: 66,
      hips: 92,
    },
    garmentMeasurements: {
      length: 58,
      chest: 78,
      waist: 70,
      hips: 96,
    },
  },
];

export const mockStores: Store[] = [
  {
    id: 's1',
    name: 'Elegance Fashion',
    market: 'Дордой',
    sector: 'Сектор 5',
    containerNumber: 'Контейнер 123',
    categories: ['Женская одежда', 'Вечерние платья'],
    contact: '+996 555 123 456',
    whatsapp: '+996555123456',
    instagram: 'elegance_fashion_kg',
    rating: 4.8,
  },
  {
    id: 's2',
    name: 'SportWear KG',
    market: 'Дордой',
    sector: 'Сектор 12',
    containerNumber: 'Контейнер 456',
    categories: ['Мужская одежда', 'Спортивная одежда'],
    contact: '+996 555 234 567',
    whatsapp: '+996555234567',
    instagram: 'sportwear_kg',
    rating: 4.5,
  },
  {
    id: 's3',
    name: 'Basic Store',
    market: 'Ош бazaar',
    sector: 'Сектор 3',
    containerNumber: 'Контейнер 789',
    categories: ['Женская одежда', 'Базовая одежда'],
    contact: '+996 555 345 678',
    whatsapp: '+996555345678',
    instagram: 'basic_store_kg',
    rating: 4.2,
  },
  {
    id: 's4',
    name: 'Denim World',
    market: 'Дордой',
    sector: 'Сектор 8',
    containerNumber: 'Контейнер 234',
    categories: ['Мужская одежда', 'Джинсы'],
    contact: '+996 555 456 789',
    whatsapp: '+996555456789',
    instagram: 'denim_world_kg',
    rating: 4.6,
  },
  {
    id: 's5',
    name: 'Office Style',
    market: 'Дордой',
    sector: 'Сектор 6',
    containerNumber: 'Контейнер 567',
    categories: ['Женская одежда', 'Офисная одежда'],
    contact: '+996 555 567 890',
    whatsapp: '+996555567890',
    instagram: 'office_style_kg',
    rating: 4.4,
  },
  {
    id: 's6',
    name: 'Kids Fashion',
    market: 'Дордой',
    sector: 'Сектор 15',
    containerNumber: 'Контейнер 890',
    categories: ['Детская одежда'],
    contact: '+996 555 678 901',
    whatsapp: '+996555678901',
    instagram: 'kids_fashion_kg',
    rating: 4.7,
  },
  {
    id: 's7',
    name: 'Formal Wear',
    market: 'Дордой',
    sector: 'Сектор 4',
    containerNumber: 'Контейнер 345',
    categories: ['Мужская одежда', 'Костюмы'],
    contact: '+996 555 789 012',
    whatsapp: '+996555789012',
    instagram: 'formal_wear_kg',
    rating: 4.9,
  },
  {
    id: 's8',
    name: 'Trendy Clothes',
    market: 'Ош бazaar',
    sector: 'Сектор 7',
    containerNumber: 'Контейнер 678',
    categories: ['Женская одежда', 'Трендовая одежда'],
    contact: '+996 555 890 123',
    whatsapp: '+996555890123',
    instagram: 'trendy_clothes_kg',
    rating: 4.3,
  },
];

export const categories = [
  'Все',
  'Женская одежда',
  'Мужская одежда',
  'Детская одежда',
  'Обувь',
  'Аксессуары',
];

export const colors = [
  'Все',
  'Черный',
  'Белый',
  'Красный',
  'Синий',
  'Зеленый',
  'Желтый',
  'Розовый',
  'Серый',
  'Коричневый',
  'Темно-синий',
  'Светло-голубой',
];

export const userRoles: UserRole[] = ['guest', 'buyer', 'store_owner', 'admin'];

export const mockSimilarProducts = (baseProduct: Product): Product[] => {
  return mockProducts
    .filter(p => p.id !== baseProduct.id)
    .filter(p => p.category === baseProduct.category)
    .map(p => ({
      ...p,
      similarityScore: Math.random() * 0.3 + 0.7, // 0.7 to 1.0
    }))
    .sort((a, b) => (b.similarityScore || 0) - (a.similarityScore || 0))
    .slice(0, 4);
};
