"""catalog schema

Revision ID: f08a05d3d852
Revises:
Create Date: 2026-10-02 06:01:39.143094

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f08a05d3d852"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Needed by the visual search tables added later; harmless if already installed.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("parent_code", sa.String(length=50), nullable=True),
        sa.Column("name_ru", sa.String(length=100), nullable=False),
        sa.Column("name_ky", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_code"], ["categories.code"], name=op.f("fk_categories_parent_code_categories")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_categories")),
    )
    op.create_table(
        "cities",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ru", sa.String(length=100), nullable=False),
        sa.Column("name_ky", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_cities")),
    )
    op.create_table(
        "colors",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ru", sa.String(length=100), nullable=False),
        sa.Column("name_ky", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_colors")),
    )
    op.create_table(
        "stores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("city_code", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("market", sa.String(length=100), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("container", sa.String(length=100), nullable=True),
        sa.Column("working_hours", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("whatsapp", sa.String(length=50), nullable=True),
        sa.Column("instagram", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'active', 'blocked')", name=op.f("ck_stores_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["city_code"], ["cities.code"], name=op.f("fk_stores_city_code_cities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("slug", name=op.f("uq_stores_slug")),
    )
    op.create_index(op.f("ix_stores_city_code"), "stores", ["city_code"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_code", sa.String(length=50), nullable=False),
        sa.Column("audience", sa.String(length=10), nullable=False),
        sa.Column("base_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "audience IN ('men', 'women', 'unisex', 'kids')",
            name=op.f("ck_products_audience_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_review', 'published', 'archived', 'blocked')",
            name=op.f("ck_products_status_valid"),
        ),
        sa.CheckConstraint("base_price_minor > 0", name=op.f("ck_products_base_price_positive")),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["categories.code"],
            name=op.f("fk_products_category_code_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_products_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("store_id", "external_id", name=op.f("uq_products_store_id")),
    )
    op.create_index(
        "ix_products_listing", "products", ["status", "category_code", "audience"], unique=False
    )
    op.create_index(op.f("ix_products_store_id"), "products", ["store_id"], unique=False)
    op.create_table(
        "product_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("color_code", sa.String(length=50), nullable=True),
        sa.Column("object_key", sa.String(length=300), nullable=True),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "object_key IS NOT NULL OR external_url IS NOT NULL",
            name=op.f("ck_product_images_has_location"),
        ),
        sa.ForeignKeyConstraint(
            ["color_code"], ["colors.code"], name=op.f("fk_product_images_color_code_colors")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("size_system", sa.String(length=20), nullable=True),
        sa.Column("size_label", sa.String(length=30), nullable=True),
        sa.Column("color_code", sa.String(length=50), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("price_override_minor", sa.BigInteger(), nullable=True),
        sa.Column("stock_mode", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("availability_status", sa.String(length=20), nullable=False),
        sa.Column("availability_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "availability_status IN ('in_stock', 'out_of_stock', 'unknown')",
            name=op.f("ck_product_variants_availability_valid"),
        ),
        sa.CheckConstraint(
            "stock_mode IN ('manual', 'exact')", name=op.f("ck_product_variants_stock_mode_valid")
        ),
        sa.CheckConstraint(
            "price_override_minor IS NULL OR price_override_minor > 0",
            name=op.f("ck_product_variants_price_override_positive"),
        ),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity >= 0",
            name=op.f("ck_product_variants_quantity_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["color_code"], ["colors.code"], name=op.f("fk_product_variants_color_code_colors")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint(
            "product_id",
            "color_code",
            "size_system",
            "size_label",
            name="uq_product_variants_combination",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_product_variants_filter",
        "product_variants",
        ["size_label", "color_code", "availability_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_index("ix_product_variants_filter", table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(op.f("ix_products_store_id"), table_name="products")
    op.drop_index("ix_products_listing", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_stores_city_code"), table_name="stores")
    op.drop_table("stores")
    op.drop_table("colors")
    op.drop_table("cities")
    op.drop_table("categories")
    # ### end Alembic commands ###
