"""variant height range

Revision ID: 05cc3b95cf24
Revises: 5e1e6893abd5
Create Date: 2026-10-02 14:49:46.754645

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05cc3b95cf24"
down_revision: str | Sequence[str] | None = "5e1e6893abd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("height_min_cm", sa.Integer(), nullable=True))
    op.add_column("product_variants", sa.Column("height_max_cm", sa.Integer(), nullable=True))
    # Autogenerate does not add CHECK constraints on existing tables.
    op.create_check_constraint(
        op.f("ck_product_variants_height_range_valid"),
        "product_variants",
        "(height_min_cm IS NULL AND height_max_cm IS NULL) OR "
        "(height_min_cm BETWEEN 50 AND 250 AND height_max_cm BETWEEN 50 AND 250 "
        "AND height_min_cm <= height_max_cm)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_product_variants_height_range_valid"), "product_variants", type_="check"
    )
    op.drop_column("product_variants", "height_max_cm")
    op.drop_column("product_variants", "height_min_cm")
    # ### end Alembic commands ###
