"""store telegram

Revision ID: 222f5a35437f
Revises: aff5b5046e8c
Create Date: 2026-10-03 03:14:19.802242

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "222f5a35437f"
down_revision: str | Sequence[str] | None = "aff5b5046e8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("telegram_chat_id", sa.String(length=40), nullable=True))
    op.add_column("stores", sa.Column("telegram_code", sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "telegram_code")
    op.drop_column("stores", "telegram_chat_id")
    # ### end Alembic commands ###
