"""store avatar

Revision ID: aefcb8e1b0e7
Revises: 05cc3b95cf24
Create Date: 2026-10-02 15:03:01.467365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aefcb8e1b0e7"
down_revision: str | Sequence[str] | None = "05cc3b95cf24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("avatar_key", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "avatar_key")
    # ### end Alembic commands ###
