"""store cabinet theme

Revision ID: 89cd038b70ce
Revises: 06057e7e8bf0
Create Date: 2026-10-03 04:42:05.770584

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89cd038b70ce"
down_revision: str | Sequence[str] | None = "06057e7e8bf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column("cabinet_theme", sa.String(length=10), server_default="black", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "cabinet_theme")
    # ### end Alembic commands ###
