"""order items and delivery

Revision ID: aff5b5046e8c
Revises: da3c0a00aad8
Create Date: 2026-10-03 03:02:09.631745

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aff5b5046e8c"
down_revision: str | Sequence[str] | None = "da3c0a00aad8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("size_label", sa.String(length=30), nullable=True),
        sa.Column("color_name", sa.String(length=100), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("price_minor > 0", name=op.f("ck_order_items_price_positive")),
        sa.CheckConstraint("quantity BETWEEN 1 AND 20", name=op.f("ck_order_items_quantity_valid")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_order_items_variant_id_product_variants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    # New columns start empty, are filled from the old one-item orders, then tightened.
    op.add_column("orders", sa.Column("items_minor", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("delivery_fee_minor", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("total_minor", sa.Integer(), nullable=True))
    op.add_column(
        "orders",
        sa.Column("delivery_method", sa.String(length=10), nullable=False, server_default="pickup"),
    )
    op.add_column("orders", sa.Column("delivery_address", sa.String(length=300), nullable=True))
    op.execute(
        """
        INSERT INTO order_items (id, order_id, product_id, variant_id, title, size_label,
                                 color_name, image_url, price_minor, quantity, reserved, position)
        SELECT gen_random_uuid(), id, product_id, variant_id, title, size_label,
               color_name, image_url, price_minor, 1, false, 0
        FROM orders
        """
    )
    op.execute(
        "UPDATE orders SET items_minor = price_minor, total_minor = price_minor, "
        "delivery_fee_minor = 0"
    )
    op.alter_column("orders", "items_minor", nullable=False)
    op.alter_column("orders", "total_minor", nullable=False)
    op.alter_column("orders", "delivery_method", server_default=None)
    op.create_check_constraint(op.f("ck_orders_total_positive"), "orders", "total_minor > 0")
    op.create_check_constraint(
        op.f("ck_orders_delivery_method_valid"),
        "orders",
        "delivery_method IN ('pickup', 'delivery')",
    )
    op.drop_constraint(op.f("fk_orders_product_id_products"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("fk_orders_variant_id_product_variants"), "orders", type_="foreignkey")
    op.drop_column("orders", "title")
    op.drop_column("orders", "product_id")
    op.drop_column("orders", "color_name")
    op.drop_column("orders", "price_minor")
    op.drop_column("orders", "variant_id")
    op.drop_column("orders", "image_url")
    op.drop_column("orders", "size_label")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("size_label", sa.VARCHAR(length=30), autoincrement=False, nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("image_url", sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    )
    op.add_column("orders", sa.Column("variant_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column(
        "orders", sa.Column("price_minor", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("color_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column("orders", sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column(
        "orders", sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_orders_variant_id_product_variants"),
        "orders",
        "product_variants",
        ["variant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_orders_product_id_products"),
        "orders",
        "products",
        ["product_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # An order goes back to holding its first item only.
    op.execute(
        """
        UPDATE orders SET title = i.title, product_id = i.product_id, variant_id = i.variant_id,
               size_label = i.size_label, color_name = i.color_name, image_url = i.image_url,
               price_minor = i.price_minor
        FROM order_items i WHERE i.order_id = orders.id AND i.position = 0
        """
    )
    op.drop_constraint(op.f("ck_orders_delivery_method_valid"), "orders", type_="check")
    op.drop_constraint(op.f("ck_orders_total_positive"), "orders", type_="check")
    op.drop_column("orders", "delivery_address")
    op.drop_column("orders", "delivery_method")
    op.drop_column("orders", "total_minor")
    op.drop_column("orders", "delivery_fee_minor")
    op.drop_column("orders", "items_minor")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    # ### end Alembic commands ###
