"""store policies

Revision ID: 465f210c0528
Revises: b594f889576a
Create Date: 2026-10-02 07:27:39.187238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "465f210c0528"
down_revision: str | Sequence[str] | None = "b594f889576a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("pickup_available", sa.Boolean(), nullable=False),
        sa.Column("delivery_available", sa.Boolean(), nullable=False),
        sa.Column("delivery_areas", sa.String(length=300), nullable=True),
        sa.Column("delivery_fee_minor", sa.Integer(), nullable=True),
        sa.Column("delivery_time", sa.String(length=200), nullable=True),
        sa.Column("try_on_at_delivery", sa.Boolean(), nullable=False),
        sa.Column("payment_methods", sa.String(length=300), nullable=True),
        sa.Column("return_days", sa.Integer(), nullable=True),
        sa.Column("return_terms", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_fee_minor IS NULL OR delivery_fee_minor >= 0",
            name=op.f("ck_store_policies_fee_not_negative"),
        ),
        sa.CheckConstraint(
            "return_days IS NULL OR return_days >= 0",
            name=op.f("ck_store_policies_return_days_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_store_policies_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_policies_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_policies")),
        sa.UniqueConstraint("store_id", "version", name=op.f("uq_store_policies_store_id")),
    )
    op.create_index(
        op.f("ix_store_policies_store_id"), "store_policies", ["store_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_store_policies_store_id"), table_name="store_policies")
    op.drop_table("store_policies")
    # ### end Alembic commands ###
