"""order item closed stock

Revision ID: 06057e7e8bf0
Revises: 5ce01435cd41
Create Date: 2026-10-03 04:11:25.921834

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06057e7e8bf0"
down_revision: str | Sequence[str] | None = "5ce01435cd41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items",
        sa.Column("closed_stock", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "closed_stock")
    # ### end Alembic commands ###
