"""accounts, membership, moderation

Revision ID: e46150f689b9
Revises: f08a05d3d852
Create Date: 2026-10-02 06:21:25.753675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e46150f689b9"
down_revision: str | Sequence[str] | None = "f08a05d3d852"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=300), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "moderation_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=10), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('store', 'product')", name=op.f("ck_moderation_log_target_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_moderation_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moderation_log")),
    )
    op.create_index(
        "ix_moderation_log_target", "moderation_log", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "store_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('owner', 'staff')", name=op.f("ck_store_members_role_valid")),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_store_members_invited_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_members_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_store_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_members")),
        sa.UniqueConstraint("store_id", "user_id", name=op.f("uq_store_members_store_id")),
    )
    op.create_index(op.f("ix_store_members_store_id"), "store_members", ["store_id"], unique=False)
    op.create_index(op.f("ix_store_members_user_id"), "store_members", ["user_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('wrong_price', 'not_available', 'wrong_photo', 'inappropriate', 'other')",
            name=op.f("ck_reports_reason_valid"),
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_reports_status_valid")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_reports_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name=op.f("fk_reports_resolved_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_product_id"), "reports", ["product_id"], unique=False)
    op.add_column("products", sa.Column("review_note", sa.Text(), nullable=True))
    op.add_column("stores", sa.Column("review_note", sa.Text(), nullable=True))
    # Autogenerate does not see changed CHECK constraints: stores gain the "rejected" status.
    op.drop_constraint(op.f("ck_stores_status_valid"), "stores", type_="check")
    op.create_check_constraint(
        op.f("ck_stores_status_valid"),
        "stores",
        "status IN ('pending_review', 'active', 'rejected', 'blocked')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE stores SET status = 'pending_review' WHERE status = 'rejected'")
    op.drop_constraint(op.f("ck_stores_status_valid"), "stores", type_="check")
    op.create_check_constraint(
        op.f("ck_stores_status_valid"),
        "stores",
        "status IN ('pending_review', 'active', 'blocked')",
    )
    op.drop_column("stores", "review_note")
    op.drop_column("products", "review_note")
    op.drop_index(op.f("ix_reports_product_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_store_members_user_id"), table_name="store_members")
    op.drop_index(op.f("ix_store_members_store_id"), table_name="store_members")
    op.drop_table("store_members")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_moderation_log_target", table_name="moderation_log")
    op.drop_table("moderation_log")
    op.drop_table("users")
    # ### end Alembic commands ###
