"""product discount

Revision ID: c1654042537d
Revises: 89cd038b70ce
Create Date: 2026-10-03 05:12:08.236779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1654042537d"
down_revision: str | Sequence[str] | None = "89cd038b70ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("discount_percent", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_products_discount_percent_valid"),
        "products",
        "discount_percent IS NULL OR discount_percent BETWEEN 1 AND 90",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_products_discount_percent_valid"), "products", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "discount_percent")
    # ### end Alembic commands ###
