"""order stages and events

Revision ID: 02bb60fbde05
Revises: 7e9bff733931
Create Date: 2026-10-02 22:57:43.052397

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02bb60fbde05"
down_revision: str | Sequence[str] | None = "7e9bff733931"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_order_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_events_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.add_column("orders", sa.Column("closing_note", sa.String(length=500), nullable=True))
    # Autogenerate does not change CHECK constraints; the new statuses are added by hand.
    op.drop_constraint(op.f("ck_orders_status_valid"), "orders", type_="check")
    op.create_check_constraint(
        op.f("ck_orders_status_valid"),
        "orders",
        "status IN ('pending_payment', 'paid', 'accepted', 'shipped', 'completed', "
        "'cancelled', 'refunded')",
    )
    op.drop_constraint(op.f("ck_payments_status_valid"), "payments", type_="check")
    op.create_check_constraint(
        op.f("ck_payments_status_valid"),
        "payments",
        "status IN ('created', 'succeeded', 'cancelled', 'refunded')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_payments_status_valid"), "payments", type_="check")
    op.create_check_constraint(
        op.f("ck_payments_status_valid"),
        "payments",
        "status IN ('created', 'succeeded', 'cancelled')",
    )
    op.drop_constraint(op.f("ck_orders_status_valid"), "orders", type_="check")
    op.create_check_constraint(
        op.f("ck_orders_status_valid"),
        "orders",
        "status IN ('pending_payment', 'paid', 'cancelled')",
    )
    op.drop_column("orders", "closing_note")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_table("order_events")
    # ### end Alembic commands ###
