"""product embeddings

Revision ID: da3c0a00aad8
Revises: 02bb60fbde05
Create Date: 2026-10-02 23:05:44.738404

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da3c0a00aad8"
down_revision: str | Sequence[str] | None = "02bb60fbde05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
        sa.Column("source", sa.String(length=600), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["product_images.id"],
            name=op.f("fk_product_embeddings_image_id_product_images"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_embeddings")),
        sa.UniqueConstraint(
            "image_id", "model_version", name=op.f("uq_product_embeddings_image_id")
        ),
    )
    op.create_index(
        op.f("ix_product_embeddings_image_id"), "product_embeddings", ["image_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_embeddings_model_version"),
        "product_embeddings",
        ["model_version"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_embeddings_model_version"), table_name="product_embeddings")
    op.drop_index(op.f("ix_product_embeddings_image_id"), table_name="product_embeddings")
    op.drop_table("product_embeddings")
    # ### end Alembic commands ###
