"""store audiences

Revision ID: e45c7c3d77ab
Revises: aefcb8e1b0e7
Create Date: 2026-10-02 15:22:11.911379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e45c7c3d77ab"
down_revision: str | Sequence[str] | None = "aefcb8e1b0e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column(
            "audiences",
            sa.ARRAY(sa.String(length=10)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    # Existing stores get the audiences of the products they already have,
    # in the fixed order women, men, kids.
    op.execute(
        """
        UPDATE stores SET audiences = found.audiences
        FROM (
            SELECT store_id,
                   array_agg(DISTINCT audience ORDER BY audience DESC)::varchar(10)[] AS audiences
            FROM products
            WHERE audience IN ('women', 'men', 'kids')
            GROUP BY store_id
        ) AS found
        WHERE found.store_id = stores.id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "audiences")
    # ### end Alembic commands ###
