"""shop sale closed stock

Revision ID: 5ce01435cd41
Revises: 1329f7d1619e
Create Date: 2026-10-03 04:00:30.765865

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ce01435cd41"
down_revision: str | Sequence[str] | None = "1329f7d1619e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shop_sales",
        sa.Column("closed_stock", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_sales", "closed_stock")
    # ### end Alembic commands ###
