import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base

EVENT_TYPES = ("product_view", "store_view", "contact_click")
CONTACT_CHANNELS = ("whatsapp", "phone", "instagram", "website")


class Event(Base):
    """One thing a visitor did. Holds no personal data: no IP address, no search
    text, no contact details; the session id is a random value from the browser."""

    __tablename__ = "events"
    __table_args__ = (
        CheckConstraint(
            "type IN ('product_view', 'store_view', 'contact_click')", name="type_valid"
        ),
        Index("ix_events_store_time", "store_id", "occurred_at"),
    )

    # Generated by the browser, so a retried request cannot count the same event twice.
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    session_id: Mapped[uuid.UUID] = mapped_column()
    type: Mapped[str] = mapped_column(String(20))
    store_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("stores.id", ondelete="CASCADE"))
    product_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("products.id", ondelete="CASCADE")
    )
    variant_id: Mapped[uuid.UUID | None] = mapped_column()
    # For contact clicks: whatsapp, phone, instagram or website.
    channel: Mapped[str | None] = mapped_column(String(20))
    # Where the visit came from: "instagram", "direct", a campaign label, ...
    source: Mapped[str | None] = mapped_column(String(50))
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
